name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          

      - name: Deploy Code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@2600:1f18:2ec0:293d:e892:767e:d75f:b7d0 << EOF
            cd /home/ec2-user/backend-app/services  # or wherever your app lives
            git pull origin master
            docker stop my-web-app || true
            docker rm my-web-app || true
            docker build --build-arg CACHE_BUSTER=$(date +%s) -t my-web-app .
            docker run -d -p 8082:8080 --name my-web-app my-web-app
          EOF
